### ISSUE TITLE
reordering PossibleFiniteStateLists in ActualFiniteStateList causes exception

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-WebServices-Community-Edition#73]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When reordering PossibleFiniteStateLists in ActualFiniteStateList the server returns an error. I have the impression that the generated ActualFiniteStateListDao is not yet correct.

The CDP4 Services replied with code InternalServerError: Internal Server Error: "exception:42703: record \"new\" has no field \"Container\""

### System Configuration
  - Create 2 PossibleFiniteStateLists containing each more than 1 state
  - Create an ActualFiniteStateList using the 2 new PossibleFiniteStateLists
  - Update ActualFiniteStateList by reordering the PossibleFiniteStateLists -> observer an exception is being raised

**Comment by samatrhea** [comment]
after some further investigation i think the following method is generated incorrectly: AddPossibleFiniteStateList. The **INSERT** statement is not what it should be in the new version: **ActualFiniteStateList_PossibleFiniteStateList** -<-> **ActualFiniteStateList_ExcludeOption**

original code
```
public bool AddPossibleFiniteStateList(NpgsqlTransaction transaction, string partition, Guid iid, CDP4Common.Types.OrderedItem possibleFiniteStateList)
        {
            using (var command = new NpgsqlCommand())
            {
                var sqlBuilder = new System.Text.StringBuilder();
            
                sqlBuilder.AppendFormat("INSERT INTO \"{0}\".\"ActualFiniteStateList_PossibleFiniteStateList\"", partition);
                sqlBuilder.AppendFormat(" (\"ActualFiniteStateList\", \"PossibleFiniteStateList\", \"Sequence\")");
                sqlBuilder.Append(" VALUES (:actualFiniteStateList, :possibleFiniteStateList, :sequence);");
                command.Parameters.Add("actualFiniteStateList", NpgsqlDbType.Uuid).Value = iid;
                command.Parameters.Add("possibleFiniteStateList", NpgsqlDbType.Uuid).Value = possibleFiniteStateList.V;
                command.Parameters.Add("sequence", NpgsqlDbType.Bigint).Value = possibleFiniteStateList.K;
            
                command.CommandText = sqlBuilder.ToString();
                command.Connection = transaction.Connection;
                command.Transaction = transaction;
                return this.ExecuteAndLogCommand(command) > 0;
            }
        }
```

new code:

```
        public bool AddExcludeOption(NpgsqlTransaction transaction, string partition, Guid iid, Guid excludeOption)
        {
            using (var command = new NpgsqlCommand())
            {
                var sqlBuilder = new System.Text.StringBuilder();
                sqlBuilder.AppendFormat("INSERT INTO \"{0}\".\"ActualFiniteStateList_ExcludeOption\"", partition);
                sqlBuilder.AppendFormat(" (\"ActualFiniteStateList\", \"ExcludeOption\")");
                sqlBuilder.Append(" VALUES (:actualFiniteStateList, :excludeOption);");

                command.Parameters.Add("actualFiniteStateList", NpgsqlDbType.Uuid).Value = iid;
                command.Parameters.Add("excludeOption", NpgsqlDbType.Uuid).Value = excludeOption;

                command.CommandText = sqlBuilder.ToString();
                command.Connection = transaction.Connection;
                command.Transaction = transaction;

                return this.ExecuteAndLogCommand(command) > 0;
            }
        }

```

**Comment by lxatrhea** [comment]
Sam's comment is not the case. This was the result of reordering of code.
The bug is there for quite a while. 
Problem is in the database. The SiteDirectory.revision_management() trigger is called when the ActualFiniteStateList_PossibleFiniteStateList table is updated. This causes an error on this row:
**has_moved := NEW."Container" <> OLD."Container";**
 The ActualFiniteStateList_PossibleFiniteStateList does not have a Container column, so an error is thrown.

**Comment by samatrhea** [comment]
so, the fix is in removing the trigger?

**Comment by lxatrhea** [comment]
> 
> 
> so, the fix is in removing the trigger?

Could be, but it might break other things too.
I think a new revision has to be created for the ActualFiniteStateList and just removing the trigger for the ActualFiniteStateList_PossibleFiniteStateList would break that functionality. That's why I commented on this issue and didn't fix it already ;)

**Comment by lxatrhea** [comment]
@samatrhea: I think there are two solutions:

1. Change the SiteDirectory.revision_management() trigger function so it checks if the Container property exists (simplest)
2. Add an extra parameter to the SiteDirectory.revision_management() trigger function that contains a boolean value that "tells" the function to check for a changed Container column. Make sure the property is set to false in case of a (cross-join) table that doesn't have a Container property.

The first is the easiest option (SQL schema update for SiteDirectory). 
We're already using hstore, so we can user the postgres **hstore(record)** command.
There's **no** noticable difference in performance when using this function for 3500 records (
**Select true from "SiteDirectory"."Thing" S** vs **Select hstore(S) ? 'Iid' from "SiteDirectory"."Thing" S**). This change is effective immediately and the problem is gone and stays away "forever".

The second option involves a lot more work and testing. More SQL changes have to be made "by hand", or SQL generation has to change. Performance benefit over option 1 seems very small. Not even milliseconds.

I prefer the first option for now, and maybe change this when SQL codegen moves to DotLiquid. But even then, the first option is the safest way.

**Comment by samatrhea** [comment]
option 1 sounds like a plane, lets do it that way
